#pragma once

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_DELAY 100
#define MOUSEKEY_WHEEL_DELAY 100
#define MOUSEKEY_WHEEL_INTERVAL 50
#define MOUSEKEY_WHEEL_TIME_TO_MAX 100

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD

#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 2000

#define COMBO_COUNT 10
#define COMBO_TERM 20
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_ONLY_FROM_LAYER 8