#pragma once
#include "config_common.h"

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM_PER_KEY

#define LEADER_NO_TIMEOUT
#define LEADER_TIMEOUT 1

#define CAPS_WORD_IDLE_TIMEOUT 3000

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define NO_MUSIC_MODE

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_ABSOLUTE_MODE 
#define CIRQUE_PINNACLE_TAP_ENABLE 