# Bad Wings Specific
TRACKPAD_ENABLE 		= yes

# General QMK
GRAVE_ESC_ENABLE		= no
SPACE_CADET_ENABLE 	= no

CAPS_WORD_ENABLE		= yes
KEY_OVERRIDE_ENABLE	= yes
COMBO_ENABLE				= no
TAP_DANCE_ENABLE		= no

LEADER_ENABLE     = yes